Add ci

diff --git a/.github/workflows/ccubank-core-dev.yml b/.github/workflows/ccubank-core-dev.yml
--- a/.github/workflows/ccubank-core-dev.yml
+++ b/.github/workflows/ccubank-core-dev.yml
@@ -54,24 +54,34 @@ jobs:
 
   deploy:
     runs-on: ubuntu-latest
-#    needs: build
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Remote to server
-        env:
-          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-
+      - name: Setup SSH Key
         run: |
-          chmod +x scripts/create_env.sh ./scripts/create_env.sh
-          chmod +x ./scripts/setup_ssh.sh
+          mkdir -p ~/.ssh
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan -H "${{ secrets.WEB_SERVER_SSH_HOST }}" >> ~/.ssh/known_hosts
 
-      - name: Server deployment
+      - name: Debug SSH Connection
+        run: |
+          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.WEB_SERVER_SSH_HOST }} "echo SSH connection successful"
+
+      - name: Debug File Existence
+        run: |
+          if [ -f "docker-compose.development.yaml" ]; then
+            echo "File exists: docker-compose.development.yaml"
+          else
+            echo "ERROR: File 'docker-compose.development.yaml' not found!"
+            exit 1
+          fi
+
+      - name: Server Deployment
         env:
-          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-          WEB_SERVER_SSH_HOST: ${{ secrets.WEB_SERVER_SSH_HOST }}
           COMPOSE_FILE_DIR: /root/ccubank
           COMPOSE_FILE_NAME: docker-compose.development.yaml
         run: bash ./scripts/deploy.sh
+
 
